#ifndef GRAVEDIGGERS_CONFIG_H
#define GRAVEDIGGERS_CONFIG_H

#define DEBUG true

#define MIN_NUMBER_OF_DEATHS 1
#define MAX_NUMBER_OF_DEATHS 5

#define CITY_COUNCIL 0

/** MESSAGE TAGS: */
#define DEATH_LIST_PUBLICATION 1
#define FUNERAL_OFFER 2

#endif
