#ifndef GRAVEDIGGERS_CONFIG_H
#define GRAVEDIGGERS_CONFIG_H

/** WORKING MODE */
#define DEBUG true

/** MAIN CONFIG */
#define MIN_NUMBER_OF_DEATHS 3
#define MAX_NUMBER_OF_DEATHS 8
#define COUNCIL_SLEEP_TIME 10
#define FUNERAL_TIME 5

/** THREADS IDS */
#define CITY_COUNCIL 0

/** MESSAGE TAGS */
#define DEATH_LIST_PUBLICATION 1
#define FUNERAL_OFFER 2

/** DISTRIBUTOR CONFIG */
#define MAX_ARRAY_SIZE MAX_NUMBER_OF_DEATHS
#define BROADCAST_EXCLUDED CITY_COUNCIL

#endif
